services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
    container_name: frontend
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/TodoList
    container_name: backend

  mongodb:
    image: mongo:7.0.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    container_name: mongodb

volumes:
  mongodb_data: